add group for adding new targets
redhat-cop/monitoring pull request #25
Opened 2020-07-27 15:24 UTC by tkummer33

### What does this PR do?
Separates playbooks into two directories monitoring-hosts and monitoring-targets.
Setup-prometheus role now creates monitoring-editors, monitoring-edit-user-1 and ssh-keypair in /tmp/ then adds the public key to the monitoring-edit-user-1 authorized_keys.
It also creates /var/prometheus_targets/ directory owned by monitoring-editors group.
Add-target role creates target definitons in  /var/prometheus_targets/ and can be run without root privileges with ansible_user in monitoring-editors group

### How should this be tested?
run the setup-prometheus-grafana and check that the /var/prometheus_targets exists and is owned by monitoring-editors group 
then run the add-targets playbook using key  /tmp/monitoring-edit-user-1_key as monitoring-edit-user-1 with ansible_become: false. Then check /var/prometheus_targets/ where directories with target definitions should appear

### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.
resolves #<number>

### Other Relevant info, PRs, etc.
Please provide link to other PRs that may be related (blocking, resolves, etc. etc.)

### People to notify
cc: @redhat-cop/monitoring

2020-07-31 12:56 UTC, pabrahamsson requested changes
Thank you @tkummer33 just one small comment inline, rest looks good.

2020-07-31 12:56 UTC, pabrahamsson commented on playbooks/infra-prometheus/README.md
> +First run of the playbook should be done with --tags="install", which installs docker on target hosts. Due to a bug in infra-ansible install-docker role it has to be run twice. Any consecutive runs c
Is there an issue open for the `infra-ansible` bug? It would be nice to link it from here so that consumers can see when it has been fixed.

2020-08-03 11:08 UTC, tkummer33 commented on playbooks/infra-prometheus/README.md
> +First run of the playbook should be done with --tags="install", which installs docker on target hosts. Due to a bug in infra-ansible install-docker role it has to be run twice. Any consecutive runs c
There isn't open issue for the infra-ansible install-docker role. I will dig deeper on this to understand what causes the  problem and open an issue or PR soon.

2020-08-04 11:21 UTC, tkummer33 commented on playbooks/infra-prometheus/README.md
> +First run of the playbook should be done with --tags="install", which installs docker on target hosts. Due to a bug in infra-ansible install-docker role it has to be run twice. Any consecutive runs c
PR https://github.com/redhat-cop/infra-ansible/pull/420/files covers this issue.

2020-08-10 12:43 UTC, pabrahamsson approved these changes
Thank you @tkummer33

2020-08-10 12:43 UTC, merged